version: '3.8'

services:
  reticketify-backend-user:
    image: reticketify-backend-user:0.0.1-SNAPSHOT
    container_name: reticketify-backend-user
    build:
      context: ./reticketify-backend-user  # Pasta onde está localizado o Dockerfile (raiz do projeto)
      network: host
    ports:
      - "8080:8080"  # Mapeamento da porta (host:container)
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Define o perfil ativo do Spring, se necessário
    depends_on:
      reticketify-db-user:   # Garantir que o banco de dados esteja iniciado antes da aplicação
        condition: service_healthy
    networks:
      - app-network-user

  reticketify-db-user:
    image: reticketify-db-user:latest
    container_name: reticketify-db-user
    build:
      context: ./reticketify-db-user  # Pasta onde está localizado o Dockerfile (raiz do projeto)
      network: host
    healthcheck:
      test: mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD -e 'SHOW DATABASES;'
      interval: 10s
      timeout: 5s
      retries: 30
    ports:
      - "3306:3306"  # Porta do banco de dados
    volumes:
      - db-data-user:/var/lib/mysql
    networks:
      - app-network-user

networks:
  app-network-user:  # Definição da rede compartilhada entre os serviços
    driver: bridge

volumes:
  db-data-user: # Volume persistente para os dados do banco de dados
